### ISSUE TITLE
Adding via ankidroid without adding html ul and li in True false type and everytime I have to set the countdown timer and check the boxes for what I have to see and unsee 

### ISSUE THREAD

**Issue by MasterKed** [ikkz/anki-eco#33]

**Comment by ikkz** [comment]
> Adding via ankidroid without adding html ul and li in True false type

I will look into how to solve this issue later

> everytime I have to set the countdown timer and check the boxes for what I have to see and unsee
I don't have Android device so these templates are not tested in ankidroid.

I don't have Android device so these templates are not tested in ankidroid. The expected behavior is settings are stored at your local device and won't  sync between devices. If your `everytime` means every device, it won't be fixed.

If the template behaves unexpectedly on your device, please describe in detail.

**Comment by ikkz** [comment]
https://github.com/ankidroid/Anki-Android/pull/16457
The page port of the latest version of ankidroid's reviewer is random, so it is impossible to access the localStorage from the last time it was opened.

You can try to roll back to the previous version. From my test, 2.16 works well.

**Comment by ikkz** [comment]
The problem of options not being saved has been fixed in the latest version

https://github.com/ikkz/anki-template/releases

**Comment by ikkz** [comment]
@MasterKed You can view the latest field requirements at https://github.com/ikkz/anki-template?tab=readme-ov-file#fields-1. Meanwhile, compatibility with the previous list format is preserved, so no changes to existing cards are necessary

Download the latest version here https://github.com/ikkz/anki-template/releases
